name: bluebubbles
description: Send iMessages on Android using BlueBubbles!

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.15.0+70
publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^3.7.2
  animated_size_and_fade: ^5.1.1
  animations: ^2.1.1
  app_links: ^7.0.0
  async_task: ^1.1.1
  audio_waveforms: ^1.3.0
  auto_size_text: ^3.0.0
  bitsdojo_window: ^0.1.6
  chunked_stream: ^1.4.2
  collection: ^1.19.1
  confetti: ^0.8.0
  connectivity_plus: ^7.0.0
  crop_your_image: ^2.0.0
  csslib: ^1.0.2
  cupertino_icons: ^1.0.8
  defer_pointer: ^0.0.2
  desktop_webview_auth:
    git:
      url: https://github.com/BlueBubblesApp/flutter_desktop_webview_auth.git
      ref: webkit2gtk-4.1
  device_info_plus: ^12.2.0
  dio: ^5.9.0
  disable_battery_optimization: # for jcenter() gradle deprecation
    git:
      url: https://github.com/BlueBubblesApp/Disable-Battery-Optimizations.git
      ref: master
  dlibphonenumber: ^1.1.51 # phone number parsing
  # todo linux
  dynamic_color: ^1.8.1
  easy_debounce: ^2.0.3
  emojis: ^0.9.9
  emoji_picker_flutter: ^4.3.0
  encrypt: ^5.0.3
  exif: ^3.3.0
  faker: ^2.2.0
  fast_contacts: ^5.0.1  # mobile only
  file_picker: ^10.3.6
  firebase_dart:
    git:
      url: https://github.com/appsup-dart/firebase_dart.git
      ref: beb79f70a2bb0e96e6bb9fdebac2ff452f138950
      path: packages/firebase_dart
  flex_color_picker: ^3.7.2
  flex_color_scheme: ^8.3.1
  flutter_acrylic: ^1.1.4
  flutter_audio_waveforms: ^1.2.1+8
  flutter_displaymode: ^0.7.0 # android only
  flutter_dotenv: ^6.0.0
  flutter_image_compress: ^2.4.0
  flutter_improved_scrolling: ^0.0.3
  flutter_isolate: ^2.1.0 # use published package instead of removed git repo
  flutter_keyboard_visibility: ^6.0.0 # no desktop support
  flutter_local_notifications: ^19.5.0 # mobile only
  flutter_map: ^8.2.2
  flutter_map_marker_popup: ^8.1.0
  flutter_markdown: ^0.7.7+1
  flutter_slidable: ^4.0.3
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.2.2
  flutter_timezone: ^5.0.1 # no desktop support
  geolocator: ^14.0.2
  gesture_x_detector: # support touchscreens properly
    git:
      url: https://github.com/BlueBubblesApp/xgesture_flutter.git
      ref: 7de6e023ff68f67af1d83f7c1303d8b973f84944
  get: ^4.7.2
  giphy_get: ^3.6.1+1
  github: ^9.25.0
  google_fonts: ^6.3.2
  google_ml_kit: ^0.20.0 # mobile only
  google_mlkit_smart_reply: ^0.13.0
  google_sign_in: ^6.2.1
  hand_signature: ^3.1.0+2
  idb_shim: ^2.6.7+1
  image: ^4.5.4
  image_picker: ^1.2.1
  image_size_getter: ^2.4.1
  intl: ^0.20.2
  js: ^0.7.2
  languagetool_textfield: ^0.0.6
  launch_at_startup: ^0.5.1
  local_auth: ^3.0.0
  local_notifier:
    git:
      url: https://github.com/BlueBubblesApp/local_notifier.git
      ref: 7526556fe2beb5c61ddede34e1992726907cd7ae
  maps_launcher: # gradle namespace issue
    git:
      url: https://github.com/pikaju/flutter-maps-launcher.git
      ref: master
  material_color_utilities: ^0.13.0
  media_kit: ^1.2.2                           # Primary package.
  media_kit_video: ^2.0.0                        # For video rendering.
  media_kit_native_event_loop: ^1.0.9            # Support for higher number of concurrent instances & better performance.
  media_kit_libs_android_video: ^1.3.8           # Android package for video native libraries.
  media_kit_libs_windows_video: ^1.0.11          # Windows package for video native libraries.
  media_kit_libs_linux: ^1.2.1                   # GNU/Linux dependency package.
  metadata_fetch: ^0.4.2
  mime_type: ^1.0.1
  mobile_scanner: ^7.1.3 # no desktop support
  msix: ^3.16.12
  multi_value_listenable_builder: ^0.0.2
  network_info_plus: ^7.0.0
  network_tools: ^6.0.5
  numberpicker: ^2.1.2
  objectbox: ^5.0.2
  objectbox_flutter_libs: any
  on_exit: ^1.0.0
  open_filex: ^4.7.0
  package_info_plus: ^9.0.0
  particles_flutter: ^1.0.1
  pasteboard: ^0.4.0
  path: ^1.9.1
  path_provider: ^2.1.5 # no web support
  pdf: ^3.11.3
  permission_handler: ^12.0.1 # mobile only
  photo_manager: ^3.7.1 # only mobile
  photo_view: ^0.15.0
  printing: ^5.14.2
  qr_flutter: ^4.1.0
  receive_intent: ^0.2.7 # mobile only
  record: ^6.1.2
  reorderables: ^0.6.0
  saver_gallery: ^4.1.0
  screen_retriever: ^0.2.0
  scroll_to_index: ^3.0.1
  secure_application:  # no linux support, gradle namespace issue
    git:
      url: https://github.com/BlueBubblesApp/secure_application.git
      ref: master
  share_plus: ^12.0.1 # sharing files not supported on Windows & Linux, todo desktop
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  simple_animations: ^5.2.0
  skeletonizer: ^2.1.0+1
  sliding_up_panel2: ^3.3.0+1
  slugify: ^2.0.0
  smooth_page_indicator: ^1.2.1
  socket_io_client: ^3.1.2
  sprung: ^3.0.1
  store_checker: # android namespace issue
    git:
      url: https://github.com/ravitejaavv/store_checker
      ref: master
  synchronized: ^3.4.0
  system_tray: ^2.0.3
  super_drag_and_drop: ^0.9.1
  supercharged: ^2.1.1
  system_info2: ^4.1.0
  tray_manager: ^0.5.2
  tuple: ^2.0.2
  unifiedpush: ^6.2.0
  universal_html: ^2.3.0 # cross-platform dart:html implementation
  universal_io: ^2.3.1 # cross-platform dart:io implementation
  url_launcher: ^6.3.2
  vcf_dart: ^1.0.3
  version: ^3.0.2
  video_player: ^2.10.1
  video_thumbnail:
    git:
      url: https://github.com/BlueBubblesApp/video_thumbnail.git
      ref: master
  window_manager: ^0.5.1
  windows_taskbar: ^1.1.2
  logger: ^2.6.2
  archive: ^4.0.7
  in_app_review: ^2.0.11
  pull_down_button: ^0.10.2
  app_install_date: ^0.1.5

dependency_overrides:
  # overrides for packages stuck on outdated versions
  http: ^1.6.0 # metadata_fetch
  js: ^0.7.2 # socket_io_client
  material_color_utilities: ^0.13.0 # flutter test SDK
  permission_handler_platform_interface: ^4.3.0 # BB permission_handler_windows
  permission_handler_windows: # https://github.com/Baseflow/flutter-permission-handler/issues/983
    git:
      url: https://github.com/BlueBubblesApp/flutter-permission-handler.git
      ref: 7912a76a3208e876c2275e1a87003ede3903abc8
      path: permission_handler_windows
  uuid: ^4.5.2 # firebase_dart
  win32: ^5.15.0 # for build issue in flutter v3.24.0
  frontend_server_client: ^4.0.0  # for build_runner issues on v3.24.0

dev_dependencies:
  build_runner: ^2.10.3
  build_verify: ^3.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_lints: ^6.0.0
  peanut: ^6.0.0
  objectbox_generator: any
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/adaptive-foreground.png"
  adaptive_icon_background: "#4990de"

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"
  image: "assets/icon/splash-foreground-dark.png"
  image_dark: "assets/icon/splash-foreground-dark.png"
  android_12:
    image: "assets/icon/splash-foreground-dark-2.png"
    image_dark: "assets/icon/splash-foreground-dark-2.png"
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "000000"

#   flutter_test:
#     sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # fonts:
  # - family: AppleColorEmoji
  #   fonts:
  #     - asset: assets/fonts/AppleColorEmoji.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/reactions/dislike-white.svg
    - assets/reactions/like-white.svg
    - assets/reactions/emphasize-white.svg
    - assets/reactions/question-white.svg
    - assets/reactions/love-white.svg
    - assets/reactions/dislike-black.svg
    - assets/reactions/like-black.svg
    - assets/reactions/emphasize-black.svg
    - assets/reactions/laugh-black.svg
    - assets/reactions/question-black.svg
    - assets/reactions/love-black.svg
    - assets/icon/moon.svg
    - assets/icon/bb-icon.svg
    - assets/images/google-sign-in.png
    - assets/images/person.png
    - assets/images/person64.png
    - assets/images/transparent.png
    - assets/images/no-video-preview.png
    - assets/images/unplayable-video.png
    - assets/icon/icon.png
    - assets/changelog/changelog.md
    - assets/icon/icon.ico
    - assets/badges/badge-1.ico
    - assets/badges/badge-2.ico
    - assets/badges/badge-3.ico
    - assets/badges/badge-4.ico
    - assets/badges/badge-5.ico
    - assets/badges/badge-6.ico
    - assets/badges/badge-7.ico
    - assets/badges/badge-8.ico
    - assets/badges/badge-9.ico
    - assets/badges/badge-10.ico
    - .env
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

msix_config:
  display_name: BlueBubbles
  publisher_display_name: BlueBubbles
  identity_name: 23344BlueBubbles.BlueBubbles
  msix_version: 1.15.0.0
  publisher: CN=BEC9154D-191E-4375-BF30-698BD4C141C4
  vs_generated_images_folder_path: windows/icons
  logo_path: assets/icon/icon.ico
  store: true
  icons_background_color: transparent
  languages: en-us
  architecture: x64
  capabilities: internetClient, location, microphone, webcam
  protocol_activation: imessage
